### ISSUE TITLE
JDKMon Download Info dialog is shown under "main window" JDK Mon

### ISSUE THREAD

**Issue by ltorok** [HanSolo/JDKMon#26]
After click on download JDK distro is dialog "JDKMon Download Info" (and this dalog has focus) shown under "main window" JDK Mon (this window is always on top). For me was whole dialog "JDKMon Download Info" under "main window" JDK Mon - this is not very user firendly.
May be related with fix for issue #24.

My OS is Windows 10.

**Comment by HanSolo** [comment]
This is because both windows are always on top and will appear centered on screen. So I won't probably fix this because this is not really an issue. As mentioned before, the app stays in the system tray and usually you only open it either when you would like to check if your installed jdk's are up to date or if you would download another one. Meaning to say the windows are usually not "used" at the same time. In case you have both open...just move one by the side.

**Comment by ltorok** [comment]
I'm not sure you know exactly what I'm talking about. Could I at least sometime in the future attach a short video?

**Comment by HanSolo** [comment]
I know exactly what you mean and I won‘t fix that because of the reason that I‘ve mentioned before.

**Comment by ltorok** [comment]
Ok. I wrote above "dialog "JDKMon Download Info" **(and this dalog has focus**)" and ""main window" JDK Mon (this window is always on top)" - this window is on top and **hasn't focus and can't moved** -> How move dialog "JDKMon Download Info" when it's all under him? The only option is from the taskbar. But this very unfriendly, unpractice and problematic. Please try You alone on clean install on Windows. Thanks.
