### ISSUE TITLE
Problem with starting JDKMon

### ISSUE THREAD

**Issue by ptnavratil** [HanSolo/JDKMon#34]
I just downloaded package from blogspot page:
**jdkmon_17.0.18-1_amd64.deb**
and installed it.

When i run it from launcher nothing happens.
When i run it from cmd i get this:
```bash
petr@probook:/opt/jdkmon/bin$ ./JDKMon 
Feb 03, 2022 10:28:29 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6aaf2814'
```
My system:
```
petr@probook 
------------ 
OS: Linux Mint 20.3 x86_64 
Host: HP ProBook 450 G8 Notebook PC 
Kernel: 5.13.0-28-generic 
Uptime: 12 mins 
Packages: 2621 (dpkg) 
Shell: bash 5.0.17 
Resolution: 1920x1080, 1920x1080, 1920x1080 
DE: Cinnamon 
WM: Mutter (Muffin) 
WM Theme: Mint-Y-Dark (Mint-Y) 
Theme: Mint-Y [GTK2/3] 
Icons: Mint-Y [GTK2/3] 
Terminal: gnome-terminal 
CPU: 11th Gen Intel i7-1165G7 (8) @ 4.700GHz 
GPU: Intel Device 9a49 
Memory: 3651MiB / 31790MiB 
```
Default java:
```
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```
Thanks for your help.

**Comment by ptnavratil** [comment]
Tried it run manually under JDK17, not working.
```bash
petr@probook:/opt/jdkmon/lib/app$ /usr/lib/jvm/jdk-17/bin/java -jar JDKMon-17.0.18.jar 
Feb 03, 2022 11:04:36 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @2a48d10f'
 ```

**Comment by HanSolo** [comment]
When running the deb, the default Java version doesn't matter because JDKMon comes bundled with it's own JDK. If you use the jar you also need to have JavaFX correctly installed. I run the deb myself on my Linux box on Ubuntu without any problem. Just to make sure you are aware of how it should work...if you start it, it will take some time before the main window will show up. First it will check for installed JDK's and by doing this it will also check JDK's it found for vulnerabilities. The app itself should then show up in the sidebar in Ubuntu. Every 3 hours it will automatically check for updates and will show notifications on the screen in case it found some.

**Comment by ptnavratil** [comment]
Hmm probably its running, i can see it in processes, but i don't see it on panel.
![image](https://user-images.githubusercontent.com/38861361/152327023-dfbc1ba0-ea52-4923-bc71-fab4452674c0.png)

**Comment by HanSolo** [comment]
Like mentioned in the readme, the system tray icon is only supported on some Linux distributions, unfortunately not on Ubuntu :(
I also have it running on a Raspberry Pi 4 with it's 64bit Raspbian and there it shows the icon. Unfortunately this is not under my control and I hope Ubuntu will be supported in the future.

**Comment by HanSolo** [comment]
So on my Ubuntu box it appears on the sidebar, not on the system tray

**Comment by ptnavratil** [comment]
I have Linux Mint with Cinnamon desktop environment, there is no sidebar. Nevemind. Anyway, thank you for your help.
