### ISSUE TITLE
Suggestion: Add more default search paths

### ISSUE THREAD

**Issue by mattiasbe** [HanSolo/JDKMon#7]
Suggestion to add more default search paths now that multiple can be added.
For example: `C:\Program Files\Zulu` on windows, but there are certainly more, for adopt open jdk etc.

**Comment by HanSolo** [comment]
Yes that's right, there are more distribution dependent paths but I won't add them all because this is already a mess on Windows but it gets even worse when using tools like sdkman etc. It's maybe a good practice to keep the installed JDKs in one place if possible and if not simply add the folders to the search path. This only has to be done once for each folder which should be ok.

**Comment by mattiasbe** [comment]
Sure it can be done, but for user conveience it's a very nice experience when you launch the app and all the different jdks are just there out of the box.
Having all different jdks in one place is not really an option as most people just use the defaults when installing them.

Maybe add a separate text file for each platform (windows, mac, linux) with locations to check and loop through them?
